### ISSUE TITLE
Display AQI, PM2.5, and PM10 as seperate items

### ISSUE THREAD

**Issue by Morid1n** [beniaminrychter/homebridge-airly#1]
Currently, after installing this plugin, you can view air quality in HomeKit by going into "Air Quality", then clicking on details.

Would it be possible to display each value as a seperate "box" in HomeKit, right on the main screen?

**Comment by cpiekacz** [comment]
There is no sensor type in HomeKit to display simple text/number value, but you could use Humidity sensor to display percentage of the norm, then it's a matter of naming it properly. It's quite simple, only few additional lines of code.

**Comment by Morid1n** [comment]
Temperature works this way. Is there no way to adapt that?

**Comment by cpiekacz** [comment]
Temperature sensor is a specific one, but of course you could use (if you don't care about measurement unit displaying degrees). FYI, here is the [list of supported sensor types by HomeKit](https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/gen/HomeKitTypes.js).
